export default {
  products: [
    {
      _id: '1',
      name: 'Beef',
      category: 'Big Meals',
      image: '/images/one.jpg',
      price: 6000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Canvas',
      category: 'Male Kicks',
      image: '/images/two.jpg',
      price: 5000,
      brand: ' Nike',
      rating: 4.2,
      numReviews: 5
    },
    {
      _id: '3',
      name: 'Fila',
      category: 'Male Kicks',
      image: '/images/three.jpg',
      price: 7000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'Adidas',
      category: 'Female Kicks',
      image: '/images/four.jpg',
      price: 7000,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      
      _id: '5',
      name: 'Skechers Women Lite Memory Foam Lace-up',
      category: 'Female Kicks',
      image: '/images/five.jpg',
      price: 3900,
      brand: 'Sketchers',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '6',
      name: 'Adidas Grand Court',
      category: 'Male Kicks',
      image: '/images/six.jpg',
      price: 4000,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '7',
      name: 'Adidas Grand Court',
      category: 'Male Kicks',
      image: '/images/seven.jpg',
      price: 4000,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '8',
      name: 'Troadlop Women Air Knitted Running Shoes',
      category: 'Womens Kicks',
      image: '/images/eight.jpg',
      price: 4000,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  
  {
      
      _id: '9',
      name: 'Skechers Women Sneaker',
      category: 'Womens Kicks',
      image: '/images/nine.jpg',
      price: 4000,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '10',
      name: 'Women 311 V2 Sneaker',
      category: 'Womens Kicks',
      image: '/images/ten.jpg',
      price: 2800,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '11',
      name: 'Women Ultra Flex-Statements Sneaker',
      category: 'Womens Kicks',
      image: '/images/eleven.jpg',
      price: 5000,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '12',
      name: 'Nike Women Ebernon Low Sneaker',
      category: 'Womens Kicks',
      image: '/images/twelve.jpg',
      price: 5000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '13',
      name: 'Women Summits-Quick Getaway Sneaker',
      category: 'Womens Kicks',
      image: '/images/thirteen.jpg',
      price: 3500,
      brand: 'Sketchers',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
    _id: '14',
      name: 'Fila Men Strada Disruptor',
      category: 'Mens Kicks',
      image: '/images/fourteen.jpg',
      price: 3500,
      brand: 'Sketchers',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
      {
        id: '15',
      name: 'Vans Men Low-Top Sneakers',
      category: 'Mens Kicks',
      image: '/images/fifteen.jpg',
      price: 1500,
      brand: 'Sketchers',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
      },
      {
        id: '16',
      name: 'M.Gemi The Lucente Mens Sneaker',
      category: 'Mens Kicks',
      image: '/images/sixteen.jpg',
      price: 1500,
      brand: 'Sketchers',
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
          
      },
      {
        id: '17',
        name: 'Nike Men VTR Sneaker',
        category: 'Mens Kicks',
        image: '/images/seventeen.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
          
      },
      {
        id: '18',
        name: 'Skechers Gomel Expected Men Loafer Shoes',
        category: 'Mens Kicks',
        image: '/images/eighteen.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '19',
        name: 'Skechers Men Elite Flex Wasik Loafer',
        category: 'Mens Kicks',
        image: '/images/nineteen.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '20',
        name: 'PUMA Men Cell Surin 2 Sneaker',
        category: 'Mens Kicks',
        image: '/images/twenty.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
          
      },
      {
        id: '21',
        name: 'PUMA Men Electron Street Sneaker',
        category: 'Mens Kicks',
        image: '/images/twentyone.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
            
      },
      {
        id: '22',
        name: 'Tennis Casual Shoes for Walking',
        category: 'Mens Kicks',
        image: '/images/twentytwo.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
          
      },
      {
        id: '23',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentythree.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '24',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentyfour.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '25',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentyfive.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '26',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentysix.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '27',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentyseven.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '28',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentyeight.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
      {
        id: '29',
        name: 'Workout Fashion Sneakers',
        category: 'Mens Kicks',
        image: '/images/twentynine.jpg',
        price: 1500,
        brand: 'Sketchers',
        rating: 4.5,
        numReviews: 8,
        countInStock: 6,
         
      },
  ]
}