export default {
  products: [
    {
      _id: '1',
      name: 'Beef',
      category: 'Big Meals',
      image: '/images/Beef.jpg',
      price: 'Ksh 600',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Burger',
      category: 'Big Meals',
      image: '/images/Burger.jpg',
      price: "Ksh 500",
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Cappuccino',
      category: 'Drinks',
      image: '/images/Cappuccino.jpg',
      price: "Ksh 700",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'CheeseCakes',
      category: 'Desserts',
      image: '/images/CheeseCakes',
      price: "Ksh 700",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      
      _id: '5',
      name: 'Chicken',
      category: 'Big Meals',
      image: '/images/Chicken.jpg',
      price: "Ksh 390",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '6',
      name: 'Chickenwing',
      category: 'Big Meals',
      image: '/images/Chickenwing.jpg',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '7',
      name: 'Coladas',
      category: 'Drinks',
      image: '/images/Coladas.jpg',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '8',
      name: 'DateTruffles',
      category: 'Desserts',
      image: '/images/DateTruffles.jpg',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  
  {
      
      _id: '9',
      name: 'Fish-Fillet',
      category: 'Big Meals',
      image: '/images/Fish-Fillet',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '10',
      name: 'FishFingers',
      category: 'Big Meals',
      image: '/images/FishFingers',
      price: "Ksh 2800",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '11',
      name: 'frenchtoast',
      category: 'Big Meals',
      image: '/images/frenchtoast.jpg',
      price: 5000,
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  }
  ]
}