export default {
  
  products: [
    {
      _id: '1',
      name: 'Beef',
      category: 'Big Meals',
      image: '/images/Beef.jpg',
      price: 'Ksh 1440',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Burger',
      category: 'Big Meals',
      image: '/images/Burger.jpg',
      price: "Ksh 1220",
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: '3',
      name: 'Cappuccino',
      category: 'Drinks',
      image: '/images/Cappuccino.jpg',
      price: "Ksh 220",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    }, {
      _id: '4',
      name: 'CheeseCakes',
      category: 'Desserts',
      image: '/images/CheeseCakes',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      
      _id: '5',
      name: 'Chicken',
      category: 'Big Meals',
      image: '/images/Chicken.jpg',
      price: "Ksh 1770",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '6',
      name: 'Chickenwing',
      category: 'Big Meals',
      image: '/images/Chickenwing.jpg',
      price: "Ksh 1220",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '7',
      name: 'Coladas',
      category: 'Drinks',
      image: '/images/Coladas.jpg',
      price: "Ksh 480",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      
      _id: '8',
      name: 'DateTruffles',
      category: 'Desserts',
      image: '/images/DateTruffles.jpg',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  
  {
      
      _id: '9',
      name: 'Fish-Fillet',
      category: 'Big Meals',
      image: '/images/Fish-Fillet',
      price: "Ksh 400",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '10',
      name: 'FishFingers',
      category: 'Big Meals',
      image: '/images/FishFingers',
      price: "Ksh 2800",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
      _id: '11',
      name: 'frenchtoast',
      category: 'Big Meals',
      image: '/images/frenchtoast.jpg',
      price: "Ksh 500",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
  },
  {
    _id: '12',
    name: 'Fruit Boosters',
    category: 'Drinks',
    image: '/images/Fruit Boosters.jpg',
    price: "Ksh 500",
    rating: 4.5,
    numReviews: 8,
    countInStock: 6,
},
{
  _id: '13',
  name: 'icecream',
  category: 'Desserts',
  image: '/images/icecream.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '14',
  name: 'Lemonades',
  category: 'Drinks',
  image: '/images/Lemonades.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '15',
  name: 'Milkshakes',
  category: 'Drinks',
  image: '/images/Milkshakes.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '16',
  name: 'muffin',
  category: 'Breakfast',
  image: '/images/muffin.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '17',
  name: 'Omelette',
  category: 'Breakfast',
  image: '/images/Omelette.jpg',
  price: "Ksh 50",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '18',
  name: 'pancake',
  category: 'Breakfast',
  image: '/images/pancake.jpg',
  price: "Ksh 50",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '19',
  name: 'Pasta',
  category: 'Big Meals',
  image: '/images/Pasta.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '20',
  name: 'pastrie',
  category: 'Desserts',
  image: '/images/pastrie.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},{
  _id: '21',
  name: 'Pizza',
  category: 'Big Meals',
  image: '/images/Pizza.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '22',
  name: 'potatoes',
  category: 'Breakfast',
  image: '/images/potatoes.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '23',
  name: 'RedVelvet',
  category: 'Desserts',
  image: '/images/RedVelvet.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},{
  _id: '24',
  name: 'Sandwiche',
  category: 'Breakfast',
  image: '/images/Sandwiche.jpg',
  price: "Ksh 500",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '25',
  name: 'sausage',
  category: 'Breakfast',
  image: '/images/sausage.jpg',
  price: "Ksh 50",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '26',
  name: 'Smoothie',
  category: 'Drinks',
  image: '/images/Smoothie.jpg',
  price: "Ksh 50",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '27',
  name: 'Sundae',
  category: 'Drinks',
  image: '/images/Sundae.jpg',
  price: "Ksh 50",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
},
{
  _id: '28',
  name: 'waffle',
  category: 'Breakfast',
  image: '/images/waffle.jpg',
  price: "Ksh 50",
  rating: 4.5,
  numReviews: 8,
  countInStock: 6,
}
  ]
}